// This is our product listing page where all products are displayed in a grid layout.
// this is an internal page that should only be accessible to authenticated users and is protected by the ProtectedRoute component.
import { useState, useMemo } from 'react';
import { useGetProductsQuery } from '../services/api';
import Navbar from '../components/Navbar';
import { Link } from 'react-router-dom';

const formatPrice = (price) => {
    return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
    }).format(price);
};

export default function ProductListPage() {
    // Here first we are fetching the products using the custom hook generated by RTK Query...
    const { data: products = [], error, isLoading } = useGetProductsQuery();
    const [searchQuery, setSearchQuery] = useState('');

    // Filter products based on search query (searches in title and category)
    // here we use useMemo to follow best practices, avoid unnecessary computations,

    const filteredProducts = useMemo(() => {
        if (!searchQuery.trim()) return products;
        const query = searchQuery.toLowerCase();
        return products.filter(
            (product) =>
                product.title.toLowerCase().includes(query) ||
                product.category.toLowerCase().includes(query)
        );
    }, [products, searchQuery]);

    return (
        <div className="min-h-screen flex flex-col bg-gray-50"> {/* Fixed invalid bg-gray-80 */}
            <Navbar />

            <main className="flex-grow p-4 sm:p-5">
                <h1 className="text-xl font-bold text-gray-800 mb-5">All Products</h1>
                <div className="flex justify-center">
                    <h1 className="text-3xl font-bold text-gray-800 mb-5">Explore our products</h1>
                </div>

                {/* Search input for filtering products */}
                <div className="max-w-2xl mx-auto mb-6">
                    <input
                        type="text"
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        placeholder="Search products by title or category..."
                        className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none"
                        aria-label="Search products"
                    />
                </div>

                {isLoading && (
                    <div className="text-center py-8">
                        <p className="text-gray-600 text-sm">Loading products...</p>
                    </div>
                )}

                {error && (
                    <div className="bg-red-50 text-red-700 p-3 rounded text-sm mb-4">
                        Failed to load products.
                    </div>
                )}

                {!isLoading && !error && (
                    <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-5 gap-8 p-6 ">
                        {filteredProducts.length > 0 ? (
                            filteredProducts.map((product) => (
                                <Link
                                    key={product.id}
                                    to={`/products/${product.id}`}
                                    className="block"
                                >
                                    <article
                                        className="bg-white rounded-lg shadow-sm overflow-hidden hover:shadow transition-shadow duration-200 focus-within:ring-1 focus-within:ring-blue-500"
                                        tabIndex={0}
                                        aria-label={`${product.title}, ${formatPrice(product.price)}, category: ${product.category}`}
                                    >
                                        <div className="aspect-square w-full bg-gray-50 flex items-center justify-center p-2">
                                            <img
                                                src={product.image}
                                                alt={product.title} // Added meaningful alt text
                                                className="object-contain w-full h-full"
                                                loading="lazy"
                                                onError={(e) => {
                                                    e.target.src = 'https://fakestoreapi.com/img/placeholder.png'; // Removed trailing spaces
                                                }}
                                            />
                                        </div>
                                        <div className="p-2.5">
                                            <span className="text-[10px] text-blue-600 font-medium uppercase tracking-wide">
                                                {product.category}
                                            </span>
                                            <h2 className="text-xs font-medium text-gray-800 mt-1 line-clamp-2 h-8">
                                                {product.title}
                                            </h2>
                                            <p className="text-sm font-semibold text-gray-900 mt-1">
                                                {formatPrice(product.price)}
                                            </p>
                                        </div>
                                    </article>
                                </Link>
                            ))
                        ) : (
                            <div className="col-span-full text-center py-10">
                                <p className="text-gray-600">No products found.</p>
                            </div>
                        )}
                    </div>
                )}
            </main>
        </div>
    );
}